### ISSUE TITLE
hello,这个最佳实践目前是有错误运行不了的。

### ISSUE THREAD

**Issue by kvkens** [Jirapo/electron-webpack-boilerplate#2]
错误贴图：

![image](https://user-images.githubusercontent.com/3817644/36944444-1ad0f048-1fd7-11e8-915d-b8cd871e957b.png)

看样子是babel的问题，麻烦看看是当前版本更新了导致吗？

我是从nowa-gui跟踪过来的，很喜欢electron去开发GUI，共同进步。

**Comment by kvkens** [comment]
我找到问题了，是没有安装`"babel-preset-react": "^6.24.1",`导致的，因为没有使用.babelrc文件，启用了options方式传入的，导致报错不明显。

**Comment by Jirapo** [comment]
惭愧

**Comment by Jirapo** [comment]
谢谢

**Comment by kvkens** [comment]
@Jirapo 一直看你写的相关electron，十分感谢，思路很好。

**Comment by Jirapo** [comment]
心花怒放~ 惭愧惭愧
